type Ingredient {
    foodId: String!,
    quantity: Float!,
    measure: Measure!,
    weight: Float!,
    food: Food!,
    foodCategory: String!
}

type NutrientInfo {
    uri: String!,
    label: String!,
    quantity: Float!,
    unit: String!
}

type Measure {
    uri: String!,
    label: String!
}

type Food {
    foodId: String!,
    label: String!
}
